apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-app-deploy
  namespace: surya-ns
  labels:
    app: recruitment-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recruitment-temp-label
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: recruitment-temp-label
    spec:
      containers:
        - name: recruitment-cont
          image: suryaa112003/recruitment-app:v1.1.1
          ports:
            - containerPort: 3000
          env:
          - name: recruitment-secret
            valueFrom:
              secretKeyRef:
                name: MONGO_URI
                value: url
          - name: recruitment-config
            valueFrom:
              configMapKeyRef:
                name: PORT
                value: PORT
          

--- 
apiVersion: v1
kind: Service
metadata:
  name: recruitment-service
  namespace: surya-ns
spec:
  selector:
    app: recruitment-temp-label
  ports:
    - port: 3001
      targetPort: 3000
  type: NodePort 