apiVersion: v1
kind: Secret
metadata:
  name: recruitment-secret
  namespace: surya-ns
type: Opaque
data:
  username: cm9vdHVzZXIK
  password: cm9vdHBhc3N3b3JkCg==
  url: bW9uZ29kYjovL3Jvb3R1c2VyOnJvb3RwYXNzd29yZEBtb25nb2RiLXNlcnZpY2U6MjcwMTcvaHJf
       c3lzdGVtP2F1dGhTb3VyY2U9YWRtaW4K
