apiVersion: v1
kind: Secret
metadata:
  name: recruitment-secret
  namespace: surya-ns
type: Opaque
stringData:
  username: rootuser
  password: rootpassword
  url: "mongodb://rootuser:rootpassword@recruitment-mongodb-service:27017/hr_system?authSource=admin"